apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-game
  namespace: cat-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-game
  template:
    metadata:
      labels:
        app: cat-game
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cat-game
          image: ghcr.io/keco-studio/cat:04c27c9ce39e55acc80ca27aba1db05b8a108e46
          ports:
            - containerPort: 80
